spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yupao?allowMultiQueries=true
    username: root
    password: 123456
  application:
    name: findfriends
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
    database: 1

server:
  port: 8001
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
#    multiple-result-sets-enabled: true
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


